---
abstract: 'Scalar::Util, List::Util, List::MoreUtils, String::Util & more (via one subroutine)'
author:
  - 'Robert Krimen <robertkrimen@gmail.com>'
build_requires:
  Test::Most: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200008, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Util-Utl
requires:
  List::MoreUtils: 0
  List::Util: 0
  Package::Pkg: 0
  Scalar::Util: 0
  String::Util: 0
version: 0.0010
